Repository zzalmyu/BE-ZZAL-MYU, pull requests merged in 2024-03, with the labels that each got.

#125 [FEAT] 태그 자동 완성 검색 시 상위 10개 반환
  src/main/java/com/prgrms/zzalmyu/domain/tag/infrastructure/TagRepositoryCustomImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/presentation/dto/res/TagResponseDto.java
  src/test/java/com/prgrms/zzalmyu/domain/tag/application/TagServiceTest.java
Labels: :rocket: Feature

#129 [REFACT] sockjs 적용
  src/main/java/com/prgrms/zzalmyu/core/config/WebSocketConfig.java
Labels: :hammer: Refactor

#131 [REFACT] 이미지 상세보기에 제목 추가
  src/main/java/com/prgrms/zzalmyu/domain/image/presentation/dto/res/ImageDetailResponse.java
Labels: :hammer: Refactor

#133 [REFACT] me 관련 응답 분리
  src/main/java/com/prgrms/zzalmyu/domain/tag/application/TagService.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/application/TagServiceImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/infrastructure/TagRepositoryCustom.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/infrastructure/TagRepositoryCustomImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/presentation/controller/TagController.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/presentation/dto/res/TagMeResponseDto.java
Labels: :hammer: Refactor

#136 [FIX] websocket 오리진 설정 수정
  src/main/java/com/prgrms/zzalmyu/core/config/WebSocketConfig.java
Labels: :red_circle: Fix

#138 [REFACT] 프론트 테스트 용 로그인 성공시 redirect url 로컬로 수정
  src/main/java/com/prgrms/zzalmyu/domain/user/oauth2/handler/OAuth2LoginSuccessHandler.java
Labels: :hammer: Refactor

#134 Feat/#125 image recommendation
  src/main/java/com/prgrms/zzalmyu/core/config/RedisConfig.java
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageMainService.java
  src/main/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageRepository.java
  src/main/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageRepositoryCustom.java
  src/main/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageRepositoryImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageTagRepositoryCustom.java
  src/main/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageTagRepositoryImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/image/presentation/controller/ImageController.java
  src/main/java/com/prgrms/zzalmyu/domain/image/presentation/dto/res/ImageResponseDto.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/application/TagService.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/application/TagServiceImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/infrastructure/TagRepositoryCustom.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/infrastructure/TagRepositoryCustomImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/infrastructure/TagUserRepository.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/presentation/controller/TagController.java
Labels: :rocket: Feature

#142 Feat/#139 image main service refact
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageMainService.java
  src/main/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageRepository.java
  src/main/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageRepositoryCustom.java
  src/main/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageRepositoryImpl.java
Labels: :hammer: Refactor

#145 Feat/#144 image like return
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageMainService.java
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageService.java
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageServiceImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/image/presentation/controller/ImageController.java
  src/main/java/com/prgrms/zzalmyu/domain/image/presentation/dto/res/ImageResponseDto.java
Labels: :hammer: Refactor

#147 [REFACT] 로직 수정
  src/main/java/com/prgrms/zzalmyu/core/properties/ErrorCode.java
  src/main/java/com/prgrms/zzalmyu/domain/user/application/UserService.java
  src/main/java/com/prgrms/zzalmyu/domain/user/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/prgrms/zzalmyu/domain/user/jwt/service/JwtService.java
  src/main/java/com/prgrms/zzalmyu/domain/user/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/prgrms/zzalmyu/domain/user/presentation/controller/UserController.java
Labels: :hammer: Refactor

#154 [FIX] 응답 오류 수정
  src/main/java/com/prgrms/zzalmyu/domain/user/jwt/filter/JwtAuthenticationProcessingFilter.java
Labels: :red_circle: Fix

#158 Refactor/#157 reissue
  src/main/java/com/prgrms/zzalmyu/core/properties/ErrorCode.java
  src/main/java/com/prgrms/zzalmyu/domain/user/application/UserService.java
  src/main/java/com/prgrms/zzalmyu/domain/user/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/prgrms/zzalmyu/domain/user/jwt/service/JwtService.java
  src/main/java/com/prgrms/zzalmyu/domain/user/presentation/controller/UserController.java
Labels: :hammer: Refactor

#149 Feat/#148 user info
  src/main/java/com/prgrms/zzalmyu/domain/user/presentation/controller/UserController.java
  src/main/java/com/prgrms/zzalmyu/domain/user/presentation/dto/res/UserInfoResponse.java
Labels: :rocket: Feature, :hammer: Refactor

#150 Feat/#146 좋아요/업로드한 이미지 태그 필터링 기능 수정
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageSearchService.java
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageSearchServiceImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageTagRepositoryImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/image/presentation/controller/ImageController.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/application/TagService.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/application/TagServiceImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/infrastructure/TagRepository.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/infrastructure/TagRepositoryCustom.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/infrastructure/TagRepositoryCustomImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/presentation/controller/TagController.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/presentation/dto/res/TagResponseDto.java
  src/test/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageTagRepositoryTest.java
Labels: :rocket: Feature, :hammer: Refactor, :red_circle: Fix

#152 [REFACTOR] Tag -> TagMeResponseDto로 수정
  src/main/java/com/prgrms/zzalmyu/domain/image/presentation/dto/res/ImageDetailResponse.java
  src/test/java/com/prgrms/zzalmyu/domain/image/application/ImageServiceTest.java
Labels: :hammer: Refactor

#160 Feat/#159 image main tag
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageSearchService.java
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageSearchServiceImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageServiceImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageTagRepositoryCustom.java
  src/main/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageTagRepositoryImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/image/presentation/controller/ImageController.java
Labels: :rocket: Feature, :hammer: Refactor

#162 [REFACTOR] CORS 허용 PATCH 추가
  src/main/java/com/prgrms/zzalmyu/core/config/WebConfig.java
Labels: :hammer: Refactor

#164 [FIX] cors header 설정
  src/main/java/com/prgrms/zzalmyu/core/config/WebConfig.java
Labels: :red_circle: Fix

#167 Feat/#167 좋아요,업로드한 짤 리스트에 isLikeYn 필드 추가
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageMainService.java
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageService.java
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageServiceImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageRepository.java
  src/main/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageRepositoryCustom.java
  src/main/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageRepositoryImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageTagRepositoryCustom.java
  src/main/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageTagRepositoryImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/image/presentation/controller/ImageController.java
  src/test/java/com/prgrms/zzalmyu/domain/image/application/ImageServiceTest.java
Labels: :hammer: Refactor

#169 [FEAT] 이미지 업로드 및 좋아요 전체 조회 및 태그 검색 기능 통합
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageSearchService.java
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageSearchServiceImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageTagRepositoryCustom.java
  src/main/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageTagRepositoryImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/image/presentation/controller/ImageController.java
  src/test/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageTagRepositoryTest.java
Labels: :rocket: Feature, :hammer: Refactor

#171 [REFACTOR] 태그 사용 횟수 증가 시 body 사용으로 수정
  src/main/java/com/prgrms/zzalmyu/domain/tag/presentation/controller/TagController.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/presentation/dto/req/TagRequestDto.java
Labels: :hammer: Refactor

#174 [FEAT] 채팅 내역 저장, 불러오기 구현
  src/main/java/com/prgrms/zzalmyu/domain/chat/application/ChatService.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/domain/entity/ChatMessage.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/infrastructure/ChatMessageRepository.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/presentation/controller/ChatController.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/presentation/controller/WebSocketController.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/presentation/dto/res/ChatHelloResponse.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/presentation/dto/res/ChatOldMessageResponse.java
Labels: :rocket: Feature

#178 [REFACTOR] swagger 설정 추가
  src/main/java/com/prgrms/zzalmyu/domain/chat/presentation/controller/ChatController.java
Labels: :hammer: Refactor

#180 Refactor/#179 chat order
  src/main/java/com/prgrms/zzalmyu/domain/chat/application/ChatService.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/domain/entity/ChatMessage.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/infrastructure/ChatMessageRepository.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/presentation/controller/ChatController.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/presentation/controller/WebSocketController.java
Labels: :hammer: Refactor

#182 Feat/#181 main refact
  src/main/java/com/prgrms/zzalmyu/domain/image/presentation/controller/ImageController.java
Labels: :hammer: Refactor

#184 [REFACTOR] 채팅 dto 통합
  src/main/java/com/prgrms/zzalmyu/domain/chat/presentation/controller/WebSocketController.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/presentation/dto/res/ChatImageResponse.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/presentation/dto/res/ChatResponse.java
Labels: :hammer: Refactor

#186 [REFACTOR] 채팅 dto 수정
  src/main/java/com/prgrms/zzalmyu/domain/chat/presentation/controller/WebSocketController.java
Labels: :hammer: Refactor

#188 [REFACTOR] cors 설정
  src/main/java/com/prgrms/zzalmyu/core/config/WebConfig.java
  src/main/java/com/prgrms/zzalmyu/core/config/WebSocketConfig.java
Labels: :hammer: Refactor

#191 [REFACTOR] 채팅 message type 추가
  src/main/java/com/prgrms/zzalmyu/domain/chat/application/ChatService.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/domain/entity/ChatMessage.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/domain/enums/MessageType.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/presentation/controller/WebSocketController.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/presentation/dto/res/ChatOldMessageResponse.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/presentation/dto/res/ChatResponse.java
Labels: :hammer: Refactor

#193 Chore/#189 security 권한 설정
  src/main/java/com/prgrms/zzalmyu/core/config/SecurityConfig.java
  src/main/java/com/prgrms/zzalmyu/domain/image/presentation/controller/ImageController.java
  src/main/java/com/prgrms/zzalmyu/domain/user/presentation/controller/UserController.java
Labels: :broom: Chore

#196 [REFACTOR] security 접근권한 일시적 수정
  src/main/java/com/prgrms/zzalmyu/core/config/SecurityConfig.java
Labels: :hammer: Refactor

#198 [FIX] logout 인증 오류 수정
  src/main/java/com/prgrms/zzalmyu/core/config/SecurityConfig.java
  src/main/java/com/prgrms/zzalmyu/domain/user/jwt/filter/JwtAuthenticationProcessingFilter.java
Labels: :red_circle: Fix

#200 [FIX] withdraw 토큰 무효화
  src/main/java/com/prgrms/zzalmyu/domain/user/application/UserService.java
  src/main/java/com/prgrms/zzalmyu/domain/user/jwt/service/JwtService.java
  src/main/java/com/prgrms/zzalmyu/domain/user/presentation/controller/UserController.java
  src/test/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageTagRepositoryTest.java
  src/test/java/com/prgrms/zzalmyu/domain/user/application/UserServiceTest.java
Labels: :red_circle: Fix

#202 [REFACTOR] swagger 접근 권한 설정
  src/main/java/com/prgrms/zzalmyu/core/config/SecurityConfig.java
Labels: :hammer: Refactor

#204 [FIX] 태그 생성 시 태그 생성 호출 tagUser 추가 생성
  src/main/java/com/prgrms/zzalmyu/domain/tag/application/TagService.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/application/TagServiceImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/presentation/controller/TagController.java
  src/test/java/com/prgrms/zzalmyu/domain/tag/application/TagServiceTest.java
Labels: :hammer: Refactor, :red_circle: Fix

#206 [FIX] 메인 페이지 접근권한 설정
  src/main/java/com/prgrms/zzalmyu/core/config/SecurityConfig.java
Labels: :red_circle: Fix

#208 Feat/#207 image like yn
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageMainService.java
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageSearchService.java
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageSearchServiceImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageRepositoryCustom.java
  src/main/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageRepositoryImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageTagRepositoryCustom.java
  src/main/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageTagRepositoryImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/image/presentation/controller/ImageController.java
Labels: :hammer: Refactor

#210 [REFACTOR] 채팅 내역 응답 수정
  src/main/java/com/prgrms/zzalmyu/domain/chat/application/ChatService.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/presentation/dto/res/ChatOldMessageResponse.java
Labels: :hammer: Refactor

#213 [REFACTOR] 입장 메시지 삭제, 이름 생성 API 분리
  src/main/java/com/prgrms/zzalmyu/domain/chat/application/ChatService.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/domain/entity/ChatMessage.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/domain/entity/ImageChatCount.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/domain/enums/MessageType.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/infrastructure/ChatMessageRepository.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/presentation/controller/ChatController.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/presentation/controller/WebSocketController.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/presentation/dto/req/ChatNameRequest.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/presentation/dto/res/ChatNameResponse.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/presentation/dto/res/ChatOldMessageResponse.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/presentation/dto/res/ChatResponse.java
Labels: :hammer: Refactor

#215 [REFACTOR] 채팅 이름 생성 api method get -> post
  src/main/java/com/prgrms/zzalmyu/domain/chat/presentation/controller/ChatController.java
Labels: :hammer: Refactor

#217 [FIX] chat nickname 접근권한 수정
  src/main/java/com/prgrms/zzalmyu/core/config/SecurityConfig.java
Labels: :hammer: Refactor

#219 [FIX] chat response 수정
  src/main/java/com/prgrms/zzalmyu/domain/chat/presentation/dto/res/ChatNameResponse.java
Labels: :red_circle: Fix

#222 [FIX] 더이상 불러올 채팅 내역 없을 때 예외 처리
  src/main/java/com/prgrms/zzalmyu/core/properties/ErrorCode.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/application/ChatService.java
Labels: :red_circle: Fix

#224 [FIX] 롤백
  src/main/java/com/prgrms/zzalmyu/domain/chat/application/ChatService.java
Labels: :red_circle: Fix

#225 Feat/#211 chat message delete
  build.gradle
  src/main/java/com/prgrms/zzalmyu/ZzalmyuApplication.java
  src/main/java/com/prgrms/zzalmyu/core/config/BatchConfig.java
  src/main/java/com/prgrms/zzalmyu/core/config/BatchScheduler.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/infrastructure/ChatMessageRepository.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/infrastructure/ImageChatCountRepository.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/presentation/dto/res/ChatResponse.java
Labels: :rocket: Feature

#227 Feat/#226 user hard delete
  src/main/java/com/prgrms/zzalmyu/core/config/BatchConfig.java
  src/main/java/com/prgrms/zzalmyu/core/config/BatchScheduler.java
  src/main/java/com/prgrms/zzalmyu/domain/user/application/UserService.java
  src/main/java/com/prgrms/zzalmyu/domain/user/infrastructure/UserRepository.java
  src/main/java/com/prgrms/zzalmyu/domain/user/jwt/entrypoint/CustomAuthenticationEntryPoint.java
  src/main/java/com/prgrms/zzalmyu/domain/user/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/prgrms/zzalmyu/domain/user/jwt/service/JwtService.java
  src/main/java/com/prgrms/zzalmyu/domain/user/oauth2/LoginSuccessResponse.java
  src/main/java/com/prgrms/zzalmyu/domain/user/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/prgrms/zzalmyu/domain/user/presentation/controller/UserController.java
  src/main/java/com/prgrms/zzalmyu/domain/user/presentation/controller/web/LoginWebController.java
  src/main/java/com/prgrms/zzalmyu/domain/user/presentation/dto/res/UserInfoResponse.java
Labels: :rocket: Feature

#230 [REFACT] main에서 중복된 이미지 나타나는 부분 수정
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageMainService.java
  src/main/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageRepositoryCustom.java
  src/main/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageRepositoryImpl.java
Labels: :hammer: Refactor

#231 [FEAT] 신고 3번 누적 hard delete 자동화
  src/main/java/com/prgrms/zzalmyu/core/config/BatchConfig.java
  src/main/java/com/prgrms/zzalmyu/core/config/BatchScheduler.java
  src/main/java/com/prgrms/zzalmyu/domain/report/application/ReportService.java
  src/main/java/com/prgrms/zzalmyu/domain/report/domain/entity/Report.java
  src/main/java/com/prgrms/zzalmyu/domain/report/infrastructure/ReportRepository.java
  src/main/java/com/prgrms/zzalmyu/domain/report/infrastructure/tasklet/ReportDeletingTasklet.java
  src/main/java/com/prgrms/zzalmyu/domain/report/presentation/controller/ReportController.java
  src/main/java/com/prgrms/zzalmyu/domain/report/presentation/dto/response/ReportDetailResponse.java
  src/main/java/com/prgrms/zzalmyu/domain/report/presentation/dto/response/ReportResponse.java
  src/test/java/com/prgrms/zzalmyu/domain/report/application/ReportServiceTest.java
Labels: :rocket: Feature
