Repository zzalmyu/BE-ZZAL-MYU, pull requests merged in 2024-02, with the labels that each got.

#3 S3 이미지 업로드 및 삭제 기능 구현
  .gitignore
  build.gradle
  src/main/java/com/prgrms/zzalmyu/core/config/AwsS3Config.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/infrastructure/ImageChatCountRepository.java
  src/main/java/com/prgrms/zzalmyu/domain/image/application/AwsS3Service.java
  src/main/java/com/prgrms/zzalmyu/domain/image/domain/entity/AwsS3.java
  src/main/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageRepository.java
  src/main/java/com/prgrms/zzalmyu/domain/image/presentation/controller/AwsS3Controller.java
  src/main/java/com/prgrms/zzalmyu/domain/image/presentation/dto/res/AwsS3RequestDto.java
  src/main/java/com/prgrms/zzalmyu/domain/image/presentation/dto/res/AwsS3ResponseDto.java
  src/main/java/com/prgrms/zzalmyu/exception/GlobalExceptionHandler.java
  src/main/resources/application.properties
Labels: :rocket: Feature, :broom: Chore

#7 [CHORE] QueryDslConfig 추가
  src/main/java/com/prgrms/zzalmyu/core/config/QueryDslConfig.java
Labels: :broom: Chore

#4 Feat/#0 security 구현
  .gitignore
  build.gradle
  src/main/java/com/prgrms/zzalmyu/core/config/RedisConfig.java
  src/main/java/com/prgrms/zzalmyu/core/config/SecurityConfig.java
  src/main/java/com/prgrms/zzalmyu/core/properties/ErrorCode.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/domain/entity/ImageChatCount.java
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageSearchService.java
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageService.java
  src/main/java/com/prgrms/zzalmyu/domain/image/domain/entity/Image.java
  src/main/java/com/prgrms/zzalmyu/domain/image/domain/entity/ImageLike.java
  src/main/java/com/prgrms/zzalmyu/domain/image/domain/entity/ImageTag.java
  src/main/java/com/prgrms/zzalmyu/domain/report/domain/entity/Report.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/domain/entity/Tag.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/domain/entity/TagUser.java
  src/main/java/com/prgrms/zzalmyu/domain/user/application/RedisService.java
  src/main/java/com/prgrms/zzalmyu/domain/user/application/UserService.java
  src/main/java/com/prgrms/zzalmyu/domain/user/domain/entity/User.java
  src/main/java/com/prgrms/zzalmyu/domain/user/domain/enums/Role.java
  src/main/java/com/prgrms/zzalmyu/domain/user/domain/enums/SocialType.java
  src/main/java/com/prgrms/zzalmyu/domain/user/exception/UserException.java
  src/main/java/com/prgrms/zzalmyu/domain/user/infrastructure/UserJPARepository.java
  src/main/java/com/prgrms/zzalmyu/domain/user/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/prgrms/zzalmyu/domain/user/jwt/service/JwtService.java
  src/main/java/com/prgrms/zzalmyu/domain/user/oauth2/CustomOAuth2User.java
  src/main/java/com/prgrms/zzalmyu/domain/user/oauth2/OAuthDto.java
  src/main/java/com/prgrms/zzalmyu/domain/user/oauth2/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/prgrms/zzalmyu/domain/user/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/prgrms/zzalmyu/domain/user/oauth2/service/CustomOAuth2UserService.java
  src/main/java/com/prgrms/zzalmyu/domain/user/oauth2/userinfo/GoogleOAuth2UserInfo.java
  src/main/java/com/prgrms/zzalmyu/domain/user/oauth2/userinfo/KakaoOAuth2UserInfo.java
  src/main/java/com/prgrms/zzalmyu/domain/user/oauth2/userinfo/NaverOAuth2UserInfo.java
  src/main/java/com/prgrms/zzalmyu/domain/user/oauth2/userinfo/OAuth2UserInfo.java
  src/main/java/com/prgrms/zzalmyu/domain/user/presentation/controller/UserController.java
  src/main/java/com/prgrms/zzalmyu/exception/GlobalExceptionHandler.java
  src/main/java/com/prgrms/zzalmyu/exception/dto/ErrorResponse.java
Labels: :rocket: Feature

#14 [REFACT] 매핑테이블에 @ManyToOne 추가
  src/main/java/com/prgrms/zzalmyu/domain/image/domain/entity/ImageLike.java
  src/main/java/com/prgrms/zzalmyu/domain/image/domain/entity/ImageTag.java
Labels: :hammer: Refactor

#8 Feat/#5 좋아요 및 업로드한 짤 태그 필터링 기능 구현
  src/main/java/com/prgrms/zzalmyu/domain/image/application/AwsS3Service.java
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageSearchService.java
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageSearchServiceImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/image/controller/ImageController.java
  src/main/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageLikeRepository.java
  src/main/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageTagRepository.java
  src/main/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageTagRepositoryCustom.java
  src/main/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageTagRepositoryImpl.java
Labels: :rocket: Feature

#22 [CHORE] h2 설정
  build.gradle
  src/main/java/com/prgrms/zzalmyu/core/config/SecurityConfig.java
Labels: :broom: Chore

#10 Feat/#9 user logout
  src/main/java/com/prgrms/zzalmyu/core/config/SecurityConfig.java
  src/main/java/com/prgrms/zzalmyu/core/properties/ErrorCode.java
  src/main/java/com/prgrms/zzalmyu/domain/user/application/RedisService.java
  src/main/java/com/prgrms/zzalmyu/domain/user/application/UserService.java
  src/main/java/com/prgrms/zzalmyu/domain/user/jwt/filter/ExceptionHandlerFilter.java
  src/main/java/com/prgrms/zzalmyu/domain/user/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/prgrms/zzalmyu/domain/user/jwt/service/JwtService.java
  src/main/java/com/prgrms/zzalmyu/domain/user/oauth2/OAuthDto.java
  src/main/java/com/prgrms/zzalmyu/domain/user/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/prgrms/zzalmyu/domain/user/presentation/controller/UserController.java
  src/main/java/com/prgrms/zzalmyu/exception/GlobalExceptionHandler.java
Labels: :rocket: Feature

#12 Feat/#11 user withdraw
  src/main/java/com/prgrms/zzalmyu/core/config/SecurityConfig.java
  src/main/java/com/prgrms/zzalmyu/core/properties/ErrorCode.java
  src/main/java/com/prgrms/zzalmyu/domain/user/application/UserService.java
  src/main/java/com/prgrms/zzalmyu/domain/user/domain/entity/User.java
  src/main/java/com/prgrms/zzalmyu/domain/user/infrastructure/UserJPARepository.java
  src/main/java/com/prgrms/zzalmyu/domain/user/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/prgrms/zzalmyu/domain/user/jwt/service/JwtService.java
  src/main/java/com/prgrms/zzalmyu/domain/user/oauth2/service/CustomOAuth2UserService.java
  src/main/java/com/prgrms/zzalmyu/domain/user/presentation/controller/UserController.java
Labels: :rocket: Feature

#18 Feat/#17 이미지 업로드 및 삭제 기능 수정 (image value 저장)
  src/main/java/com/prgrms/zzalmyu/domain/image/application/AwsS3Service.java
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageSearchServiceImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/image/domain/entity/Image.java
  src/main/java/com/prgrms/zzalmyu/domain/image/presentation/controller/AwsS3Controller.java
  src/main/java/com/prgrms/zzalmyu/domain/image/presentation/dto/res/AwsS3ResponseDto.java
Labels: :rocket: Feature, :hammer: Refactor

#23 Feat/#20 이미지 신고하기 구현
  src/main/java/com/prgrms/zzalmyu/domain/report/application/ReportService.java
  src/main/java/com/prgrms/zzalmyu/domain/report/infrastructure/ReportRepository.java
  src/main/java/com/prgrms/zzalmyu/domain/report/presentation/controller/ReportController.java
  src/test/java/com/prgrms/zzalmyu/domain/report/application/ReportServiceTest.java
Labels: :rocket: Feature

#26 [REFACT] refresh token 유효성 검사 실패 시 예외 처리
  src/main/java/com/prgrms/zzalmyu/domain/report/presentation/controller/ReportController.java
  src/main/java/com/prgrms/zzalmyu/domain/user/jwt/filter/JwtAuthenticationProcessingFilter.java
Labels: :hammer: Refactor

#28 Feat/#27 security refactoring
  src/main/java/com/prgrms/zzalmyu/core/config/SecurityConfig.java
  src/main/java/com/prgrms/zzalmyu/domain/user/application/UserService.java
  src/main/java/com/prgrms/zzalmyu/domain/user/domain/enums/SocialType.java
  src/main/java/com/prgrms/zzalmyu/domain/user/infrastructure/UserRepository.java
  src/main/java/com/prgrms/zzalmyu/domain/user/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/prgrms/zzalmyu/domain/user/jwt/service/JwtService.java
  src/main/java/com/prgrms/zzalmyu/domain/user/oauth2/service/CustomOAuth2UserService.java
  src/test/java/com/prgrms/zzalmyu/domain/report/application/ReportServiceTest.java
Labels: :hammer: Refactor

#30 Feat/#29 이미지 신고 내역 조회 구현
  src/main/java/com/prgrms/zzalmyu/domain/report/application/ReportService.java
  src/main/java/com/prgrms/zzalmyu/domain/report/infrastructure/ReportRepository.java
  src/main/java/com/prgrms/zzalmyu/domain/report/presentation/controller/ReportController.java
  src/main/java/com/prgrms/zzalmyu/domain/report/presentation/dto/response/ReportDetailResponse.java
  src/main/java/com/prgrms/zzalmyu/domain/user/application/UserService.java
Labels: :rocket: Feature

#33 Refact/#32 admin login
  src/main/java/com/prgrms/zzalmyu/common/redis/RedisService.java
  src/main/java/com/prgrms/zzalmyu/core/config/SecurityConfig.java
  src/main/java/com/prgrms/zzalmyu/domain/user/application/UserService.java
  src/main/java/com/prgrms/zzalmyu/domain/user/domain/entity/User.java
  src/main/java/com/prgrms/zzalmyu/domain/user/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/prgrms/zzalmyu/domain/user/jwt/service/JwtService.java
  src/main/java/com/prgrms/zzalmyu/domain/user/oauth2/CustomOAuth2User.java
  src/main/java/com/prgrms/zzalmyu/domain/user/oauth2/LoginSuccessResponse.java
  src/main/java/com/prgrms/zzalmyu/domain/user/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/prgrms/zzalmyu/domain/user/oauth2/service/CustomOAuth2UserService.java
Labels: :hammer: Refactor

#36 Feat/#15 image service query
  src/main/java/com/prgrms/zzalmyu/core/properties/ErrorCode.java
  src/main/java/com/prgrms/zzalmyu/domain/image/application/AwsS3Service.java
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageRemoveService.java
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageService.java
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageServiceImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/image/controller/ImageController.java
  src/main/java/com/prgrms/zzalmyu/domain/image/exception/ImageException.java
  src/main/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageLikeRepository.java
  src/main/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageRepository.java
  src/main/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageTagRepository.java
  src/main/java/com/prgrms/zzalmyu/domain/image/presentation/controller/AwsS3Controller.java
  src/main/java/com/prgrms/zzalmyu/domain/image/presentation/controller/ImageController.java
  src/main/java/com/prgrms/zzalmyu/domain/image/presentation/dto/res/ImageDetailResponse.java
Labels: :rocket: Feature, :hammer: Refactor

#39 [REFACT] ImageRemoveService 쿼리 수정
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageRemoveService.java
  src/main/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageLikeRepository.java
Labels: :hammer: Refactor

#40 Feat/#24 delete reported image
  src/main/java/com/prgrms/zzalmyu/core/properties/ErrorCode.java
  src/main/java/com/prgrms/zzalmyu/domain/report/application/ReportService.java
  src/main/java/com/prgrms/zzalmyu/domain/report/exception/ReportException.java
  src/main/java/com/prgrms/zzalmyu/domain/report/infrastructure/ReportRepository.java
  src/main/java/com/prgrms/zzalmyu/domain/report/presentation/controller/ReportController.java
Labels: :rocket: Feature

#42 Feat/#35 s3 image tag add
  src/main/java/com/prgrms/zzalmyu/core/properties/ErrorCode.java
  src/main/java/com/prgrms/zzalmyu/domain/image/application/AwsS3Service.java
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageService.java
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageServiceImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageUploadService.java
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageUploadServiceImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/image/presentation/controller/ImageController.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/exception/TagException.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/infrastructure/TagRepository.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/infrastructure/TagUserRepository.java
Labels: :rocket: Feature, :hammer: Refactor

#43 Feat/#19 tag service
  src/main/java/com/prgrms/zzalmyu/core/properties/ErrorCode.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/application/TagService.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/application/TagServiceImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/infrastructure/TagRepository.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/infrastructure/TagRepositoryCustom.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/infrastructure/TagRepositoryCustomImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/presentation/controller/TagController.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/presentation/dto/res/TagResponseDto.java
  src/test/java/com/prgrms/zzalmyu/domain/tag/application/TagServiceTest.java
Labels: :rocket: Feature

#44 [REFACT] 신고 상세 정보 응답에 태그 정보 추가
  src/main/java/com/prgrms/zzalmyu/domain/report/application/ReportService.java
  src/main/java/com/prgrms/zzalmyu/domain/report/presentation/dto/response/ReportDetailResponse.java
Labels: :hammer: Refactor

#45 Feat/#37 신고 내역 조회 구현
  src/main/java/com/prgrms/zzalmyu/domain/report/application/ReportService.java
  src/main/java/com/prgrms/zzalmyu/domain/report/domain/entity/Report.java
  src/main/java/com/prgrms/zzalmyu/domain/report/infrastructure/ReportRepository.java
  src/main/java/com/prgrms/zzalmyu/domain/report/infrastructure/ReportRepositoryCustom.java
  src/main/java/com/prgrms/zzalmyu/domain/report/infrastructure/ReportRepositoryCustomImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/report/presentation/controller/ReportController.java
  src/main/java/com/prgrms/zzalmyu/domain/report/presentation/dto/response/ReportDetailResponse.java
  src/main/java/com/prgrms/zzalmyu/domain/report/presentation/dto/response/ReportResponse.java
Labels: :rocket: Feature

#48 Feat/# 46 swagger and controller (dto수정)
  build.gradle
  src/main/java/com/prgrms/zzalmyu/core/config/SwaggerConfiguration.java
  src/main/java/com/prgrms/zzalmyu/domain/image/presentation/controller/ImageController.java
  src/main/java/com/prgrms/zzalmyu/domain/image/presentation/dto/req/TagListRequestDto.java
  src/main/java/com/prgrms/zzalmyu/domain/image/presentation/dto/res/ImageDetailResponse.java
  src/main/java/com/prgrms/zzalmyu/domain/report/presentation/controller/ReportController.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/presentation/controller/TagController.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/presentation/dto/req/TagCreateRequestDto.java
  src/main/java/com/prgrms/zzalmyu/domain/user/presentation/controller/UserController.java
Labels: :hammer: Refactor, :broom: Chore

#50 [TEST] user test
  src/main/java/com/prgrms/zzalmyu/domain/user/application/UserService.java
  src/test/java/com/prgrms/zzalmyu/domain/user/application/UserServiceTest.java
Labels: :test_tube: Test

#53 Feat/#51 report test & fix
  src/main/java/com/prgrms/zzalmyu/domain/image/application/AwsS3Service.java
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageUploadServiceImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/image/domain/entity/Image.java
  src/main/java/com/prgrms/zzalmyu/domain/report/application/ReportService.java
  src/main/java/com/prgrms/zzalmyu/domain/report/presentation/dto/response/ReportResponse.java
  src/main/resources/static/index.html
  src/test/java/com/prgrms/zzalmyu/domain/report/application/ReportServiceTest.java
Labels: :hammer: Refactor, :red_circle: Fix, :test_tube: Test

#55 cd 파일 생성
  .github/workflows/cd_gradle.yml
Labels: :rocket: Feature, :broom: Chore

#59 [FIX] kakao 로그인 오류 수정
  src/main/java/com/prgrms/zzalmyu/domain/user/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/prgrms/zzalmyu/domain/user/oauth2/userinfo/KakaoOAuth2UserInfo.java
Labels: :red_circle: Fix

#61 [REFACT] login 성공 시 처리
  src/main/java/com/prgrms/zzalmyu/domain/user/oauth2/handler/OAuth2LoginSuccessHandler.java
Labels: :hammer: Refactor

#64 [TEST] ImageServiceTest 구현
  src/test/java/com/prgrms/zzalmyu/domain/image/application/ImageServiceTest.java
Labels: :test_tube: Test

#67 Refactor/#62 request form
  src/main/java/com/prgrms/zzalmyu/domain/image/application/AwsS3Service.java
  src/main/java/com/prgrms/zzalmyu/domain/image/presentation/controller/ImageController.java
Labels: :rocket: Feature, :hammer: Refactor, :red_circle: Fix

#73 Feat/# 72 image service refact (delete 메서드, image 좋아요 메서드)
  src/main/java/com/prgrms/zzalmyu/core/properties/ErrorCode.java
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageRemoveService.java
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageService.java
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageServiceImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageRepository.java
  src/main/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageTagRepositoryImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/image/presentation/controller/ImageController.java
  src/test/java/com/prgrms/zzalmyu/domain/image/application/ImageRemoveServiceTest.java
  src/test/java/com/prgrms/zzalmyu/domain/image/application/ImageServiceTest.java
Labels: :hammer: Refactor

#71 [REFACT] Image 좋아요 ,업로드 짤 리스트,Report 페이징 처리
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageService.java
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageServiceImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageRepository.java
  src/main/java/com/prgrms/zzalmyu/domain/image/presentation/controller/ImageController.java
  src/test/java/com/prgrms/zzalmyu/domain/image/application/ImageServiceTest.java
Labels: :hammer: Refactor

#75 [FEAT] cors 설정
  src/main/java/com/prgrms/zzalmyu/core/config/WebConfig.java
Labels: :rocket: Feature

#78 Feat/#76 report service refactor 검증로직 추가
  src/main/java/com/prgrms/zzalmyu/core/properties/ErrorCode.java
  src/main/java/com/prgrms/zzalmyu/domain/image/infrastructure/ImageTagRepository.java
  src/main/java/com/prgrms/zzalmyu/domain/report/application/ReportService.java
  src/main/java/com/prgrms/zzalmyu/domain/report/infrastructure/ReportRepository.java
Labels: :hammer: Refactor

#81 Feat/#80 taguser repository refact
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageUploadServiceImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/infrastructure/TagUserRepository.java
Labels: :hammer: Refactor

#83 [FEAT] getReports()함수에 paging 적용
  src/main/java/com/prgrms/zzalmyu/domain/report/application/ReportService.java
  src/main/java/com/prgrms/zzalmyu/domain/report/infrastructure/ReportRepository.java
  src/main/java/com/prgrms/zzalmyu/domain/report/presentation/controller/ReportController.java
  src/test/java/com/prgrms/zzalmyu/domain/report/application/ReportServiceTest.java
Labels: :rocket: Feature

#85 [FIX] 카카오 이메일 중복 문제 해결
  src/main/java/com/prgrms/zzalmyu/domain/user/oauth2/service/CustomOAuth2UserService.java
Labels: :red_circle: Fix

#87 [FEAT] 전체 이미지 반환 함수 구현
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageService.java
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageServiceImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/image/presentation/controller/ImageController.java
Labels: :rocket: Feature

#89 Feat/#88 tag search
  src/main/java/com/prgrms/zzalmyu/domain/tag/application/TagService.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/application/TagServiceImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/domain/entity/Tag.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/infrastructure/TagRepositoryCustom.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/infrastructure/TagRepositoryCustomImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/presentation/controller/TagController.java
Labels: :rocket: Feature

#91 [TEST] 태그 자동완성 기능 테스트
  src/test/java/com/prgrms/zzalmyu/domain/tag/application/TagServiceTest.java
Labels: :test_tube: Test

#98 Feat/#94 chat
  build.gradle
  src/main/java/com/prgrms/zzalmyu/core/config/WebSocketConfig.java
  src/main/java/com/prgrms/zzalmyu/core/properties/ErrorCode.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/application/ChatService.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/exception/ChatException.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/presentation/controller/ChatController.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/presentation/dto/req/ChatHelloRequest.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/presentation/dto/req/ChatPhotoRequest.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/presentation/dto/res/ChatHelloResponse.java
  src/main/java/com/prgrms/zzalmyu/domain/chat/presentation/dto/res/ChatImageResponse.java
Labels: :rocket: Feature, :broom: Chore

#100 [FEAT] ssl keystore추가
  src/main/resources/ssl/keystore.p12
Labels: :rocket: Feature, :broom: Chore

#96 Feat/#95 유저가 업로드한 사진들의 태그 검색 자동완성 기능 구현 & 이미지 제목 추가 및 관련 로직 추가
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageUploadService.java
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageUploadServiceImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/image/domain/entity/Image.java
  src/main/java/com/prgrms/zzalmyu/domain/image/presentation/controller/ImageController.java
  src/main/java/com/prgrms/zzalmyu/domain/image/presentation/dto/req/ImageUploadRequestDto.java
  src/main/java/com/prgrms/zzalmyu/domain/image/presentation/dto/res/AwsS3ResponseDto.java
  src/main/java/com/prgrms/zzalmyu/domain/report/application/ReportService.java
  src/main/java/com/prgrms/zzalmyu/domain/report/presentation/dto/response/ReportDetailResponse.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/application/TagService.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/application/TagServiceImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/infrastructure/TagRepositoryCustom.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/infrastructure/TagRepositoryCustomImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/presentation/controller/TagController.java
  src/test/java/com/prgrms/zzalmyu/domain/report/application/ReportServiceTest.java
  src/test/java/com/prgrms/zzalmyu/domain/tag/application/TagServiceTest.java
Labels: :rocket: Feature, :test_tube: Test

#102 [FEAT] title 추가
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageUploadServiceImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/image/domain/entity/AwsS3.java
Labels: :hammer: Refactor

#106 [FEAT] 이미지 업로드 시 이미지 파일을 progressive 로 변경
  src/main/java/com/prgrms/zzalmyu/core/properties/ErrorCode.java
  src/main/java/com/prgrms/zzalmyu/domain/image/application/AwsS3Service.java
Labels: :rocket: Feature

#108 [REFACT] 로그인 성공 후 리다이렉트 주소 수정
  src/main/java/com/prgrms/zzalmyu/domain/user/oauth2/handler/OAuth2LoginSuccessHandler.java
Labels: :hammer: Refactor

#112 Feat/#111 image upload refact
  src/main/java/com/prgrms/zzalmyu/domain/image/presentation/controller/ImageController.java
  src/main/java/com/prgrms/zzalmyu/domain/image/presentation/dto/req/ImageUploadRequestDto.java
Labels: :hammer: Refactor

#110 Feat/#109 report detail response
  src/main/java/com/prgrms/zzalmyu/domain/image/presentation/controller/ImageController.java
  src/main/java/com/prgrms/zzalmyu/domain/report/application/ReportService.java
  src/main/java/com/prgrms/zzalmyu/domain/report/presentation/controller/ReportController.java
  src/main/java/com/prgrms/zzalmyu/domain/report/presentation/dto/response/ReportDetailDto.java
  src/main/java/com/prgrms/zzalmyu/domain/report/presentation/dto/response/ReportDetailResponse.java
  src/test/java/com/prgrms/zzalmyu/domain/report/application/ReportServiceTest.java
Labels: :rocket: Feature

#114 Feat/#113 image remove service
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageRemoveService.java
  src/test/java/com/prgrms/zzalmyu/domain/image/application/ImageRemoveServiceTest.java
Labels: :hammer: Refactor

#118 Feat/#116 report 리스트/상세 페이지에서 제공 정보 변경
  src/main/java/com/prgrms/zzalmyu/domain/report/application/ReportService.java
  src/main/java/com/prgrms/zzalmyu/domain/report/presentation/dto/response/ReportDetailResponse.java
  src/main/java/com/prgrms/zzalmyu/domain/report/presentation/dto/response/ReportResponse.java
  src/test/java/com/prgrms/zzalmyu/domain/report/application/ReportServiceTest.java
Labels: :hammer: Refactor

#117 [REFACTOR] Tag 검색 컨트롤러 RequestParam 이름 input -> keyword로 변경
  src/main/java/com/prgrms/zzalmyu/domain/tag/application/TagService.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/application/TagServiceImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/tag/presentation/controller/TagController.java
Labels: :hammer: Refactor

#120 Feat/#119 image remove service
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageRemoveService.java
Labels: :hammer: Refactor

#122 [REFACTOR] 입력받은 keyword가 빈 값일 시 빈 리스트를 반환한다.
  src/main/java/com/prgrms/zzalmyu/domain/tag/application/TagServiceImpl.java
Labels: :rocket: Feature, :hammer: Refactor

#127 [FEAT] 업로드 및 좋아요 누른 사진에서 태그 필터링 검색 시 tagCount 증가로직 추가
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageSearchService.java
  src/main/java/com/prgrms/zzalmyu/domain/image/application/ImageSearchServiceImpl.java
  src/main/java/com/prgrms/zzalmyu/domain/image/presentation/controller/ImageController.java
  src/main/java/com/prgrms/zzalmyu/domain/image/presentation/dto/req/TagSearchRequestDto.java
Labels: :rocket: Feature
